let daysArray = [
	"Lunes",//0
	"Martes",//1
	"Miércoles",//2
	"Jueves",//3
	"Viernes",//4
	"Sábado"//5
]

let monthsArray = [
	{
		name:"Marzo",
		totalDays:12,
		startingDay:0,
		endingDay:5,
		startingDate:18,
		endingDate:30,
		monthNumber:"03"
	},{
		name:"Abril",
		totalDays:26,
		startingDay:0,
		endingDay:1,
		startingDate:1,
		endingDate:30,
		monthNumber:"04"
	},{
		name:"Mayo",
		totalDays:27,
		startingDay:2,
		endingDay:4,
		startingDate:1,
		endingDate:31,
		monthNumber:"05"
	},
	{
		name:"Junio",
		totalDays:25,
		startingDay:5,
		endingDay:5,
		startingDate:1,
		endingDate:29,
		monthNumber:"06"
	},
	{
		name:"Julio",
		totalDays:27,
		startingDay:0,
		endingDay:2,
		startingDate:1,
		endingDate:31,
		monthNumber:"07"
	},
	{
		name:"Agosto",
		totalDays:27,
		startingDay:3,
		endingDay:5,
		startingDate:1,
		endingDate:31,
		monthNumber:"08"
	},{
		name:"Septiembre",
		totalDays:25,
		startingDay:0,
		endingDay:0,
		startingDate:2,
		endingDate:30,
		monthNumber:"09"
	},{
		name:"Octubre",
		totalDays:27,
		startingDay:1,
		endingDay:3,
		startingDate:1,
		endingDate:31,
		monthNumber:"10"
	},{
		name:"Noviembre",
		totalDays:26,
		startingDay:4,
		endingDay:5,
		startingDate:1,
		endingDate:30,
		monthNumber:"11"
	},{
		name:"Diciembre",
		totalDays:26,
		startingDay:0,
		endingDay:1,
		startingDate:2,
		endingDate:31,
		monthNumber:"12"
	}

]